# SPDX-FileCopyrightText: 2024 Fishbait <Fishbait@git.ml>
# SPDX-FileCopyrightText: 2024 John Space <bigdumb421@gmail.com>
# SPDX-FileCopyrightText: 2024 Piras314 <p1r4s@proton.me>
# SPDX-FileCopyrightText: 2024 Tadeo <td12233a@gmail.com>
# SPDX-FileCopyrightText: 2024 username <113782077+whateverusername0@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 whateverusername0 <whateveremail>
# SPDX-FileCopyrightText: 2025 Benjamin Velliquette <32338704+bVelliquette@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Terkala <appleorange64@gmail.com>
# SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: antag
  id: Changeling
  name: roles-antag-changeling-name
  antagonist: true
  setPreference: true
  objective: roles-antag-changeling-description
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5h
  - !type:SpeciesRequirement
    inverted: true
    species:
    - IPC
  guides: [ Changelings ]

