# SPDX-FileCopyrightText: 2025 TheHolyAegis <76066612+TheHolyAegis@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 TheHolyAegis <sanderkamphuis719@gmail.com>
# SPDX-FileCopyrightText: 2025 mkanke-real <mikekanke@gmail.com>
# SPDX-FileCopyrightText: 2026 Tea <Xerithin@gmail.com>
#
# SPDX-License-Identifier: MIT

- type: job
  id: SpaceCowboy
  name: Space Cowboy
  description: ghost-role-information-space-cowboy-description
  setPreference: false
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 36000 #10 hrs
  weight: 0
  playTimeTracker: JobSpaceCowboy
  startingGear: SpaceCowboyGear
  requireAdminNotify: false
  joinNotifyCrew: false
  canBeAntag: false
  access:
  - SpaceCowboy
  special:
  - !type:AddComponentSpecial
    components:
    - type: ReplacementAccent
      accent: cowboy


- type: startingGear
  id: SpaceCowboyGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    shoes: ClothingShoesBootsLaceup
    outerClothing: ClothingOuterVest
    id: SpaceCowboyIDCard
    eyes: ClothingEyesGlassesSunglasses
    back: ClothingBackpackSatchelLeather
    ears: ClothingHeadsetFreelance
    belt: ClothingBeltHolster
    pocket1: ClothingMaskGasMerc
    pocket2: ClothingHandsKnuckleDusters

