# SPDX-FileCopyrightText: 2025 Josh Hilsberg <thejoulesberg@gmail.com>
# SPDX-FileCopyrightText: 2025 JoulesBerg <104539820+JoulesBerg@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 TheHolyAegis <76066612+TheHolyAegis@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 TheHolyAegis <sanderkamphuis719@gmail.com>
# SPDX-FileCopyrightText: 2025 wilowzeta <willowzeta632146@proton.me>
# SPDX-FileCopyrightText: 2026 taydeo <td12233a@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: CentralCommandIntern
  name: Central Command Intern
  description: ghost-role-information-centcom-intern-description
  playTimeTracker: JobCentralCommandIntern
  setPreference: false
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 360000 #100 hrs
  - !type:DepartmentTimeRequirement
    department: CentralCommand
    time: 72000 #20 hours
  weight: 0
  startingGear: CentralCommandInternGear
  icon: JobIconCentralCommandIntern
  requireAdminNotify: true
  joinNotifyCrew: false
  supervisors: job-supervisors-central-commanders
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: CentralCommandInternGear
  equipment:
    id: CentcomInternPDA
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesCommand
    ears: ClothingHeadsetCentCom
    pocket2: RubberStampCentComIntern
    gloves: ClothingHandsGlovesHop
    belt: BoxFolderCentComClipboard
    back: ClothingBackpackCentcom
    jumpsuit: ClothingUniformJumpsuitCentcomAgent
  inhand:
  - BriefcaseBrownFilled
  storage:
    back:
    - BookSpaceLaw
