# SPDX-FileCopyrightText: 2025 Josh Hilsberg <thejoulesberg@gmail.com>
# SPDX-FileCopyrightText: 2025 Tay <td12233a@gmail.com>
# SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: job
  id: Magistrate
  name: Magistrate
  description: "Serve directly under CentComm. As the stations central legal authority, you authorize executions, extended detentions, warrants, etc."
  playTimeTracker: JobMagistrate
  requirement:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 360000 #100 hrs
  weight: 20
  startingGear: MagistrateGear
  icon: "JobIconMagistrate"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - Command
  - CentralCommand
  - Brig
  - External
  - Maintenance
  - Lawyer
  - Security
  - GenpopEnter
  - GenpopLeave
  - Cryogenics
  - Engineering
  - Medical
  - Research
  - Cargo
  - Service
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: MagistrateGear
  equipment:
    id: MagistratePDA
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetCentCom
    pocket2: RubberStampMagistrate
  inhand:
  - BriefcaseBrownFilled
  storage:
    back:
    - Flash
    - BookSpaceLaw
