# SPDX-FileCopyrightText: 2022 Kara <lunarautomaton6@gmail.com>
# SPDX-FileCopyrightText: 2022 Leon Friedrich <60421075+ElectroJr@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Pancake <Pangogie@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 2024 Aidenkrz <aiden@djkraz.com>
# SPDX-FileCopyrightText: 2024 Errant <35878406+Errant-4@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Kira Bridgeton <161087999+Verbalase@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Mr. 27 <45323883+Dutch-VanDerLinde@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 PoTeletubby <108604614+PoTeletubby@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 PoTeletubby <ajcraigaz@gmail.com>
# SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Tay <td12233a@gmail.com>
# SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

#Wizard outfit startingGear definitions.
- type: startingGear
  id: WizardBlueGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorDarkBlue
    head: ClothingHeadHatWizard
    back: ClothingBackpack # Wizard backpack?
    outerClothing: ClothingOuterWizard
    shoes: ClothingShoesWizard
    id: WizardIDCard
    ears: ClothingHeadsetAltCommand
    belt: ClothingBeltWand
    pocket1: WizardTeleportScroll
    pocket2: WizardsGrimoire
  storage:
    back:
    - BoxSurvivalSlots # Goobstation - Slots Based Survival Boxes

- type: startingGear
  id: WizardRedGear
  parent: WizardBlueGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorRed
    head: ClothingHeadHatRedwizard
    outerClothing: ClothingOuterWizardRed

- type: startingGear
  id: WizardVioletGear
  parent: WizardBlueGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorPurple
    head: ClothingHeadHatVioletwizard
    outerClothing: ClothingOuterWizardViolet

- type: chameleonOutfit
  id: WizardChameleonOutfit
  name: roles-antag-wizard-name
  startingGear: WizardBlueGear
  equipment:
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    neck: ClothingNeckLGBTPin
    gloves: ClothingHandsGlovesColorBlack
