# SPDX-FileCopyrightText: 2025 TheHolyAegis <76066612+TheHolyAegis@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 TheHolyAegis <sanderkamphuis719@gmail.com>
# SPDX-FileCopyrightText: 2025 empty0set <16693552+empty0set@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 empty0set <empty0set@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: job
  id: CommandMaid
  name: job-name-command-maid
  description: job-description-command-maid
  playTimeTracker: JobCommandMaid
  requirements:
    - !type:RoleTimeRequirement
      role: JobJanitor
      time: 3600 #1 hr
  startingGear: CommandMaidGear
  icon: "JobIconCommandMaid"
  supervisors: job-supervisors-command
  setPreference: false
  overrideConsoleVisibility: true
  access:
  - Service
  - Janitor
  - Kitchen
  - Maintenance
  - Command
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: GarbageDay
    prototype: WeaponRevolverInspector

- type: startingGear
  id: CommandMaidGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtJanimaid
    id: CommandMaidPDA
    gloves: ClothingHandsGlovesJanitor
    ears: ClothingHeadsetCommandService
    belt: ClothingBeltJanitorFilled
    shoes: ClothingShoesGaloshes
