# SPDX-FileCopyrightText: 2025 Josh Hilsberg <thejoulesberg@gmail.com>
# SPDX-FileCopyrightText: 2025 JoulesBerg <104539820+JoulesBerg@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Tay <td12233a@gmail.com>
# SPDX-FileCopyrightText: 2025 kbarkevich <24629810+kbarkevich@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 mkanke-real <mikekanke@gmail.com>
# SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: playTimeTracker
  id: JobInternalAffairsAgent

- type: playTimeTracker
  id: JobMagistrate

- type: playTimeTracker
  id: CentralCommandIntern

- type: playTimeTracker
  id: SpaceCowboyTime
