# SPDX-FileCopyrightText: 2026 Steve <marlumpy@gmail.com>
# SPDX-FileCopyrightText: 2026 marc-pelletier <113944176+marc-pelletier@users.noreply.github.com>
# SPDX-FileCopyrightText: 2026 willow <willowzeta632146@proton.me>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# - type: job
#   id: Geneticist
#   name: id-card-job-geneticist
#   description: job-description-geneticist
#   playTimeTracker: JobGeneticist
#   # requirements:
#   #   - !type:DepartmentTimeRequirement
#   #     department: Medical
#   #     time: 18000  # 5 hrs total med
#   startingGear: GeneticistGear
#   icon: "JobIconGeneticist"
#   requireAdminNotify: false
#   joinNotifyCrew: true
#   supervisors: job-supervisors-medical
#   canBeAntag: true
#   access:
#     - Maintenance
#     - Medical
#     - Research
#   special: []

- type: startingGear
  id: GeneticistGear
  equipment:
    id: GeneticistPDA
    ears: ClothingHeadsetMedical
    pocket2: HandheldGeneticAnalyzer
