# SPDX-FileCopyrightText: 2024 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 2024 Aidenkrz <aiden@djkraz.com>
# SPDX-FileCopyrightText: 2024 Aviu00 <93730715+Aviu00@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 BombasterDS <115770678+BombasterDS@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 DevilishMilk <bluscout78@yahoo.com>
# SPDX-FileCopyrightText: 2024 John Space <bigdumb421@gmail.com>
# SPDX-FileCopyrightText: 2024 Kira Gbedan <161087999+Verbalase@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Piras314 <92357316+Piras314@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Piras314 <p1r4s@proton.me>
# SPDX-FileCopyrightText: 2024 Rank #1 Jonestown partygoer <mary@thughunt.ing>
# SPDX-FileCopyrightText: 2024 Tadeo <td12233a@gmail.com>
# SPDX-FileCopyrightText: 2024 Teapug <159912420+Teapug@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Theapug <159912420+Teapug@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 flyingkarii <123355664+flyingkarii@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Catazeus <200477155+Catazeus@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Mish <bluscout78@yahoo.com>
# SPDX-FileCopyrightText: 2025 YaraaraY <158123176+YaraaraY@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
# SPDX-FileCopyrightText: 2025 willowzeta <willowzeta632146@proton.me>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: job
  id: NanotrasenRepresentative
  name: Nanotrasen Representative
  description: "Represent NT, Send reports back to them on the station's situation, Inform the heads of anything CentCom orders them to do."
  playTimeTracker: JobNanotrasenRepresentative
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 144000 #40 hrs
    - !type:RoleTimeRequirement
      role: JobInternalAffairsAgent
      time: 36000 #10 hrs
  weight: 20
  startingGear: NanotrasenRepresentativeGear
  icon: "JobIconNanotrasenRepresentative"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - CentralCommand
  - Brig
  - External
  - Cryogenics
  - Maintenance
  - Engineering
  - Medical
  - Research
  - Command
  - Cargo #funkystation
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: NanotrasenRepresentativeGear
  equipment:
    id: NanotrasenRepresentativePDA
    ears: ClothingHeadsetAltCentCom
    pocket1: UniqueNanorepLockerTeleporter
  storage:
    back:
    - Flash
    - BluespaceLifelineImplanter
