- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafePistolRg2
  name: RG-2 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponEnergyGunEnergyPistol
      amount: 4
