- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafePistolPlasma
  name: P-25 jackal safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponPlasmaAdder
      amount: 4
    - id: PhoronCanister
      amount: 8

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeRiflePlasma
  name: P-106 medina safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponPlasmaAkurra
      amount: 4
    - id: PhoronCanister
      amount: 12
