# SPDX-FileCopyrightText: 2026 W.xyz() <84605679+pirakaplant@users.noreply.github.com>
#
# SPDX-License-Identifier: MIT

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafePistolRg2
  name: RG-2 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponEnergyGunEnergyPistol
      amount: 4
