- type: job
  id: Chaplain
  name: job-name-chaplain
  description: job-description-chaplain
  playTimeTracker: JobChaplain
  startingGear: ChaplainGear
  icon: "JobIconChaplain"
  supervisors: job-supervisors-hop
  access:
  - Chapel
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles
    - type: CultResistant # Funky cult

- type: startingGear
  id: ChaplainGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: ChaplainPDA
    ears: ClothingHeadsetService
  storage:
    back:
    - Bible
    - RubberStampChaplain

# funkystation - cry about it
- type: loadoutEffectGroup
  id: ChaplainAnnabelleRighteousness
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: JobChaplain
      time: 72000 #20 hrs
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 36000 #10 hrs
