- type: latheRecipe
  id: WeaponEnergyGunEnergyPistol
  result: WeaponEnergyGunEnergyPistol
  completetime: 5
  materials:
    Glass: 1000
    Steel: 1000
    Plastic: 500
    Silver: 100 

- type: latheRecipe
  id: WeaponTeslaGun
  result: WeaponTeslaGun
  completetime: 15
  materials:
    Steel: 3000
    Gold: 1000
    Plasma: 1000
    Uranium: 500
    Glass: 500
    Plastic: 500