#- type: antag
#  id: HeadRev
#  name: roles-antag-rev-head-name
#  antagonist: true
#  setPreference: true
#  objective: roles-antag-rev-head-objective
#  guides: [ Revolutionaries ]

- type: antag
  id: BloodCultist
  name: roles-antag-cult-name
  antagonist: true
  setPreference: true
  objective: roles-antag-cult-objective
  guides: [ BloodCult ]

- type: startingGear
  id: BloodCultistGear
  storage:
    back:
    - SheetRunedMetal10
#    - ClothingEyesGlassesSunglasses
#    - EncryptionKeySyndie # Goobstation
#    - RevsFastDrawImplanter # Goobstation
