# SPDX-FileCopyrightText: 2024 AJCM-git <60196617+AJCM-git@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 2024 Arendian <137322659+Arendian@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Baptr0b0t <152836416+Baptr0b0t@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Golinth <amh2023@gmail.com>
# SPDX-FileCopyrightText: 2024 PrPleGoo <PrPleGoo@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 slarticodefast <161409025+slarticodefast@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 B_Kirill <cool.bkirill@yandex.ru>
# SPDX-FileCopyrightText: 2025 Ilya Mikheev <me@ilyamikcoder.com>
# SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: securityIcon
  id: SecurityIcon
  abstract: true
  priority: 3
  offset: 1
  locationPreference: Right
  isShaded: true

- type: securityIcon
  parent: SecurityIcon
  id: SecurityIconDischarged
  icon:
    sprite: /Textures/Interface/Misc/security_icons.rsi
    state: hud_discharged

- type: securityIcon
  parent: SecurityIcon
  id: SecurityIconIncarcerated
  icon:
    sprite: /Textures/Interface/Misc/security_icons.rsi
    state: hud_incarcerated

- type: securityIcon
  parent: SecurityIcon
  id: SecurityIconParoled
  icon:
    sprite: /Textures/Interface/Misc/security_icons.rsi
    state: hud_paroled

- type: securityIcon
  parent: SecurityIcon
  id: SecurityIconSuspected
  icon:
    sprite: /Textures/Interface/Misc/security_icons.rsi
    state: hud_suspected

- type: securityIcon
  parent: SecurityIcon
  id: SecurityIconWanted
  icon:
    sprite: /Textures/Interface/Misc/security_icons.rsi
    state: hud_wanted

- type: securityIcon
  id: MindShieldIcon
  priority: 2
  locationPreference: Right
  layer: Mod
  isShaded: true
  icon:
    sprite: /Textures/Interface/Misc/job_icons.rsi
    state: MindShield
