# SPDX-FileCopyrightText: 2024 KingFroozy <froozy345@mail.ru>
# SPDX-FileCopyrightText: 2024 Tadeo <td12233a@gmail.com>
# SPDX-FileCopyrightText: 2025 Mish <bluscout78@yahoo.com>
# SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: job
  id: Roboticist
  name: job-name-roboticist
  description: job-description-roboticist
  playTimeTracker: JobRoboticist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 14400 #4 hrs
  startingGear: RoboticistGear
  icon: "JobIconRoboticist"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Robotics
  - Maintenance
  alternateTitles:
  - RoboticistBiomechanicalEngineer
  - RoboticistMechatronicSpecialist
  - RoboticistCybertronicTechnician

- type: startingGear
  id: RoboticistGear
  equipment:
    ears: ClothingHeadsetRobotics

- type: jobAlternateTitle
  id: RoboticistBiomechanicalEngineer
  name: job-name-alt-roboticist-1

- type: jobAlternateTitle
  id: RoboticistMechatronicSpecialist
  name: job-name-alt-roboticist-2

- type: jobAlternateTitle
  id: RoboticistCybertronicTechnician
  name: job-name-alt-roboticist-3
