# SPDX-FileCopyrightText: 2024 John Space <bigdumb421@gmail.com>
# SPDX-FileCopyrightText: 2024 fishbait <gnesse@gmail.com>
# SPDX-FileCopyrightText: 2025 Terkala <appleorange64@gmail.com>
# SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: antag
  id: Blob
  name: roles-antag-blob-name
  antagonist: true
  setPreference: true
  objective: roles-antag-blob-objective
  guides: [ Blob ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 54000 # 15h
