# SPDX-FileCopyrightText: 2024 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 2024 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 2024 Tadeo <td12233a@gmail.com>
# SPDX-FileCopyrightText: 2024 Vasilis <vasilis@pikachu.systems>
# SPDX-FileCopyrightText: 2024 slarticodefast <161409025+slarticodefast@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
# SPDX-FileCopyrightText: 2026 Komoni <131829655+Komonighub@users.noreply.github.com>
# SPDX-FileCopyrightText: 2026 ParadoxumOfficial <79181105+ParadoxumOfficial@users.noreply.github.com>
#
# SPDX-License-Identifier: MIT

name: "Labels: Untriaged"

on:
  issues:
    types: [opened]
  pull_request_target:
    types:
    - opened
    - reopened
    - ready_for_review

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "Status: Untriaged"
