# SPDX-FileCopyrightText: 2022 mirrorcult <lunarautomaton6@gmail.com>
# SPDX-FileCopyrightText: 2024 Tadeo <td12233a@gmail.com>
# SPDX-FileCopyrightText: 2024 slarticodefast <161409025+slarticodefast@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
# SPDX-FileCopyrightText: 2026 Komoni <131829655+Komonighub@users.noreply.github.com>
#
# SPDX-License-Identifier: MIT

name: "Labels: Review"

on:
  pull_request_target:
    types: [review_requested]

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "Status: Needs Review"
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: "Status: Awaiting Changes"
