name: "Labels: Changes Requested"

on:
  pull_request_review:
    types: [submitted]

jobs:
  labelling:
    if: github.event.review.state == 'changes_requested'
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.BOT_TOKEN }}
        labels: "Status: Awaiting Changes"
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        github_token: ${{ secrets.BOT_TOKEN }}
        labels: "Status: Needs Review"
