name: "Approval"

on: 
  pull_request_review:
    types:
      - submitted

jobs:
  check_approval:
    runs-on: ubuntu-latest
    if: github.event.review.user.login == 'taydeo' && github.event.review.state == 'approved'
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "APPROVED"
